services:
  db:
    image: ernestas2n2kas/transport-system-db:latest
    container_name: TransportSystemDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: ernestas2n2kas/transport-pgadmin:latest
    container_name: project_pgadmin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: